# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false

  config.vm.provider :libvirt do |libvirt|
  # Don't forget to create your storage pool
    libvirt.storage_pool_name="virtMachine"
    libvirt.driver="kvm"
    libvirt.uri="qemu:///system"
    libvirt.memory = 4096
    libvirt.graphics_type = "none"
    libvirt.cpus = 1
    libvirt.management_network_name = 'vagrant-libvirt1'
    libvirt.management_network_address = '192.168.124.0/24'
  end

  # ELK server.
  config.vm.define "logs" do |logs|
    logs.vm.hostname = "logs.test"
    logs.vm.network :private_network, ip: "192.168.124.90"
    logs.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/elk/main.yml"
      ansible.inventory_path = "provisioning/elk/inventory"
      ansible.become = true
    end
  end

  # Web server.

end